### ISSUE TITLE
Missing marker types

### ISSUE THREAD

**Issue by lmachens** [lmachens/arkesia.gg-web#1]
We like to add these markers to the map:

- [x] Mokoko seeds (Mokoko seed icon)
- [x] Secret passage (yellow star icon?)
- [x] Food ingredient
- [x] Viewpoint
- [x] Boss
- [x] World Boss
- [x] Treasure Map Entry
- [x] Dungeon
- [x] Triport (teleporter)
- [x] Play instrument (for secret rooms / locations, etc)
- [x] Hidden Story (exclamation mark icon)
- [x] Comment
- [x] Treasure Box (might be obsolete in western release, didn't find one yet where there is supposed to be one)
- [x] NPCs
- [x] Stations

![image](https://user-images.githubusercontent.com/10058950/154799139-3d565615-6226-427e-9a03-2d322dc3378c.png)

I think some of these types requires additional properties like a `name` (e.g. the name of the boss) and a screenshot (#2). 
Any other properties required?

**Comment by Sturmfunke** [comment]
Properties for markers:

- Name (mandatory)
- Screenshot (optional)
- Description (optional)
- Gear score requirement (optional, relevant only for certain marker types like world bosses and islands).

**Comment by Sturmfunke** [comment]
node categories:

- Collectibles (Mokoko seeds, food ingredients, etc)
- Locations (triports, normal dungeons, portals
- Entrances (?)  (nodes in cities to endgame contests like cube, tower, arena, chaos dungeon, raid, platin field, etc)
- Services
- Miscellaneous

**Comment by Sturmfunke** [comment]
Some categories from the ingame map:
![image](https://user-images.githubusercontent.com/50137120/154811473-1b81e107-1a74-4924-9d7d-43d2c06475bb.png)
![image](https://user-images.githubusercontent.com/50137120/154811475-acd241ff-a040-4d48-ba11-8274075561b2.png)
![image](https://user-images.githubusercontent.com/50137120/154811477-c6eff130-438e-4f14-8850-959b40261ec8.png)
![image](https://user-images.githubusercontent.com/50137120/154811483-ee86a502-372a-48be-b214-97139b755378.png)
![image](https://user-images.githubusercontent.com/50137120/154811490-e98cd044-4c57-4454-8a51-7d3890d17ae9.png)
![image](https://user-images.githubusercontent.com/50137120/154811507-b7e1ff92-7307-4769-ae2d-a536a9b94ef8.png)

**Comment by lmachens** [comment]
> Properties for markers:
> 
> * Name (mandatory)
> * Screenshot (optional)
> * Description (optional)
> * Gear score requirement (optional, relevant only for certain marker types like world bosses and islands).
> 
> Edit: There are certain other requirements, that could be added either in the description or as an additional property. For example a certain emote or song is needed to be able to start, open or interact with something.
> 
> Spinning it further: If it is a separate property, you could add a search function in the future where users can search for e.g. "Forest Minuet" and then get a list of all maps (with the corresponding marker highlighted) where this song is needed in order to access something. Such search function could also be used to list all maps which contain the searched marker type / unique marker. Clicking on a map in the search results would open it and highlight the marker(s) on that map.

I will start with `name`,  `screenshot` and `description` which is useful for every node.

**Comment by Sturmfunke** [comment]
"Play instrument"->  I suggest renaming it to "Play song". The player learns different songs, like the "Song of Resonance", which is important to open passages and such. The instrument the player plays for the songs is different for each class, but has no impact on the game, it has no relevance.

**Comment by ryantaplin** [comment]
- Mokoko seeds (Mokoko seed icon)
- Secret passage (yellow star icon?)
- Food ingredient
- Viewpoint
- Boss
- World Boss
- Treasure Map Entry
- Dungeon
- Triport (teleporter)✔️ 
- Portal Statue (home recall)✔️ 
- Play instrument (for secret rooms / locations, etc)
- Hidden Story (exclamation mark icon)
- Comment
- Treasure Box (might be obsolete in western release, didn't find one yet where there is supposed to be one)
- NPCs
- Exchange
   - Sea Bounty Exchange (Peyto & Fermata)✔️ 
   - Trade Skill Material Exchange (All City?) ✔️ 
   - Rapport Exchange (All City?)✔️
   - Island Soul Exchange (Opher Island) ✔️
   - Giants Heart Exchange (Wisdom Isle) ✔️ 
   - Masterpiece Exchange (Sunflower Island)
   - World Tree Leaf Exchange (Some City?) ✔️ 
   - Ignea Token Exchange (All City)✔️ 
   - Ominous Star Exchange (Punika)
- Merchant
   - General Merchant ✔️ 
   - Special Merchant
      - Luck (Stones & Cards) ✔️ 
      - Luxury Goods ✔️  
   - Trade Merchant (used for a whole range of things; abyss, bloodshards, rift pieces etc) ✔️
   - Potion Merchant ✔️ 
   - Food Merchant x2 ✔️
   - Gear Merchant ✔️
   - Ingredient Merchant ✔️
   - Trade skill Merchant ✔️
- Stations 
   - Map Exchange ✔️ 
   - Adventure Helper ✔️ 
   - Chaos Dungeon ✔️ 
   - Guardian Raid ✔️ 
   - Abyssal Dungeon ✔️ 
   - Tower ✔️ 
   - Cube ✔️ 
   - Gem Expert ✔️ 
   - Stone Cutter ✔️ 
   - Gear Honing ✔️ 
   - Skill Tree Transfer ✔️ 
   - Platinum Mines ✔️ 
   - Proving Grounds ❓ 
   - Chef ✔️ 
   - Mail ✔️ 
   - Repairer ✔️ 
   - Alchemist ✔️ 
   - Crafting & Processing ✔️ 
   - Skin Mod ✔️ 
   - Market Broker✔️ 
   - Pet Manager ✔️ 
   - Currency Broker ✔️

**Comment by lmachens** [comment]
Thank you for the list.
So we need icons for these types:

Secret passage (yellow star icon?) ❓
Another Story ❓
Treasure Map Entry ❓ using X mark, similar to how it's show own the treasure map - could maybe do with better icon?
Comment ❓
Treasure Box ❓ (might be obsolete in western release, didn't find one yet where there is supposed to be one)
Proving Grounds ❓
TBD ❗ ❗ ❗


What is TBD?
I would search for good icons on https://game-icons.net/, resize to 64x64 and add a 3px black border.

**Comment by ryantaplin** [comment]
It was suppose to be under World/Islands, indent screwed up.

Yeah, you could put 'Another Story' under a normal quest marker but depends if you want it to stand out.

**Comment by Sturmfunke** [comment]
> Yeah, you could put 'Another Story' under a normal quest marker but depends if you want it to stand out as different or not.

I would give the "Another Story" node the yellow quest marker, that's how they are marked ingame. Right now its this book, which is a graphic not from the game.
![image](https://user-images.githubusercontent.com/50137120/160351814-44d6e2d1-e55c-4d0d-8beb-b78f6b9bb825.png)

Everything else seems to be done in this issue.

**Comment by Sturmfunke** [comment]
I just realized, when trying to add nodes, that we are missing excavation for the trade skills. 
![image](https://user-images.githubusercontent.com/50137120/161325477-098aa683-ceff-4c55-9b0d-da7d2aec7549.png)
The relics you can excavate are not marked on the map ingame, but the locations are fixed and adding the nodes to the map would be extremely helpful for many players.
