### ISSUE TITLE
Tortoyk map issues

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/arkesia.gg-web#118]
- Remove map: https://www.arkesia.gg/maps/Tortoyk/Tortoyk%20Parapara%20Cruise "Tortoyk Parapara Cruise".
This map isn't used (its the same as https://www.arkesia.gg/maps/Tortoyk/Seaswept%20Woods) and a research could only find one single source listing this map without any comment.

- Map thumbnail missing in Mokoko Village: https://www.arkesia.gg/maps/Tortoyk/Mokoko%20Village?tile=7
See bottom left: 
![image](https://user-images.githubusercontent.com/50137120/160446488-b49923e9-0be1-416d-8cd2-e8b4b1ad8f75.png)
This map is this house in Mokoko-Village (I dont know what it's called in English, couldn't find the name):
![image](https://user-images.githubusercontent.com/50137120/160449549-39c1be25-dfe8-4423-a516-f982797f609d.png)
Also, when adding a node, the view switches to that map. And while I am on that map, right clicking doesn't bring me back to Mokoko Village, but to the world map. These issues might be all connected.

- Map missing in Mokoko Village: Village Chief's Home
![image](https://user-images.githubusercontent.com/50137120/160450767-3b3f2d58-3f26-4176-bc84-5ad1dda21d0e.png)

**Comment by lmachens** [comment]
Thx! 
I can't find the correct map tiles for the additional layers mokoko village, thus, I would like to remove them.
