### ISSUE TITLE
Optimizing Node Summary

### ISSUE THREAD

**Issue by ryantaplin** [lmachens/arkesia.gg-web#123]
It has become clear that some nodes are not as important as others, and the node summary is becoming overwhelmingly bloated (see image below).

It would be nice if we had the ability to whitelist certain nodes to determine which should be displayed on the summary.

Thinking aloud here, maybe this could be achieved in a similar way to how we did the node search filtering... where `summariseNodes` and `summariseNode` determine whether the node should be displayed in the summary or not.
```
{
    name: "General Orientation",
    includes: ["Continent", "Dungeon", "Island"],
    summariseNodes: true // where this creates a default for all node type's in this category.
    types: [
      {
        name: "Map Transition",
        icon: "minimap_symbol_7.webp",
        summariseNode: false //where this overrides the summariseNodes value, if blank or null defaults to false.
      },
...
}
```

![image](https://user-images.githubusercontent.com/11903234/161382106-379e5e76-2945-47df-af2c-1dccaa037863.png)

**Comment by lmachens** [comment]
I excluded "Map Transition". Anything else you like to exclude?
You can add the types like this to https://github.com/lmachens/arkesia.gg-web/pull/134/commits/6e3944810643c41ebb29581746dcc95e48bb0afe

**Comment by ryantaplin** [comment]
Hmm I see why it was done this why but it's a bit limited... This list could quite easily get really big.

I would remove all icons in this category too; https://github.com/lmachens/arkesia.gg-web/blob/b4bf4acb82424399528eb907e600e091b9543138/app/lib/static.ts#L776

But there's easily 20+ icons in that category.

**Comment by ryantaplin** [comment]
```
const nodesToFilter : string[] = ["Map Transition", "Ankumo Mountain", "Arid Path", "Battlebound Plains", "Bilbrin Forest", "Blackrose Chapel", "Borea's Domain", "Croconys Seashore", "Delphi Township", "Dyorika Plain", "Flowering Orchard", "Forest of Giants", "Lakebar", "Leyar Terrace", "Loghill", "Luterra Castle", "Medrick Monastery", "Melody Forest", "Mokoko Village", "Mount Zagoras", "Nebelhorn", "Ozhorn Hill", "Port City Changhun", "Prideholme", "Prisma Valley", "Rattan Hill", "Red Sand Desert", "Rethramis Border", "Riza Falls", "Saland Hill", "Scraplands", "Seasweapt Woods", "Skyreach Steppe", "Stern", "Sunbright Hill", "Sweetwater Forest", "Totrich", "Twilight Mists", "Wavestrand Port", "Windbringer Hills",]

if (nodesToFilter.includes(location.areaNode.type)) {
  return;
}
```

**Comment by lmachens** [comment]
You are right, it's not the best solution. I was not sure if there are only a few nodes excluded.
I updated it and added `hideInSummary` to the `nodeCategories`.
This should solve this issue:
https://github.com/lmachens/arkesia.gg-web/pull/137/files#diff-360bd9be8cd272e93060e8fb8963c3fb64ab5e51ea2d9a6f11450c8c38e78bf5
