### ISSUE TITLE
Continent Multi-Map View Toggle

### ISSUE THREAD

**Issue by ryantaplin** [lmachens/arkesia.gg-web#16]
I don't know if this is possible to take each map as a frame and put them together side by side, but it would be nice to give users the ability to enable a multi-map view for continents.

This will allow users two very different experience depending on their use of the map:
 1) Get an overview of all maps in a continent 
 2) Focus and drill in on a specific map in their continent 

It's not ideal looking at a map individually for some usecases, like when doing cross-map objectives (i.e hidden stories) and having the navigate between each map as you progress - but actually it may be nicer in most cases to have a separate single map view to help users to focus on the map they're interested in.

Example below:
![image](https://user-images.githubusercontent.com/11903234/155369052-203f1e0a-0368-43ff-8474-12ce7d5be806.png)

![image](https://user-images.githubusercontent.com/11903234/155370917-0a6e3fa9-1ba2-428a-9a56-09540b718481.png)

**Comment by lmachens** [comment]
This would be difficult to implement with the system we have right now, and I don't think it's required anymore. What do you think? I'll close it for now.
