### ISSUE TITLE
Node Image Expanding Improvements

### ISSUE THREAD

**Issue by ryantaplin** [lmachens/arkesia.gg-web#17]
- Ability to click image thumbnail and see an expanded view of it.
- Ability to add multiple images to a single node and cycle through them.
![image](https://user-images.githubusercontent.com/11903234/155375655-3387d897-4730-4d67-9d69-4a2956559eda.png)

**Comment by lmachens** [comment]
> Ability to add multiple images to a single node and cycle through them.
I added #33 to discuss this idea
