### ISSUE TITLE
Shorten titles in tooltips, add character limit to titles and description

### ISSUE THREAD

**Issue by Sturmfunke** [lmachens/arkesia.gg-web#21]
- Titles should have a character limit and maybe be shortened in tooltips or have a forced line break.
- Descriptions should have a character limit and a forced line break.

Without whitespace:
![image](https://user-images.githubusercontent.com/50137120/155384172-ca28a694-a5ca-4453-83bc-214a81e9e14d.png)
![image](https://user-images.githubusercontent.com/50137120/155384320-a0865aa6-57f3-4b2a-9423-6adb9dc43a2e.png)

With whitespace:
![image](https://user-images.githubusercontent.com/50137120/155384421-fd5f5d91-9ed4-4d71-9368-b12108059086.png)
![image](https://user-images.githubusercontent.com/50137120/155384440-25983e47-4e36-4970-a119-2715da69875c.png)

**Comment by ryantaplin** [comment]
Description's look like they already truncated, but title's aren't.
![image](https://user-images.githubusercontent.com/11903234/155386931-450fa1f0-c01b-475c-aca5-ef06c4d95491.png)
![image](https://user-images.githubusercontent.com/11903234/155387043-44571393-d404-4098-a321-1425de374b1e.png)
