### ISSUE TITLE
Weird Pixel Offset When Releasing Node (Editing Location)

### ISSUE THREAD

**Issue by ryantaplin** [lmachens/arkesia.gg-web#63]
When editing a node and moving it's location the node jumps a few pixels from the location selected when releasing RMB. See example below:

![Animation](https://user-images.githubusercontent.com/11903234/156929466-0f854a25-987d-4bae-b409-e136c36a1fef.gif)

**Comment by lmachens** [comment]
Looks like it's related to https://github.com/Leaflet/Leaflet/pull/7446.
It will be fixed when a new version of leaflet is released.

In the meantime, I would recommend moving markers with the left mouse button, which doesn't behave like this.

**Comment by ryantaplin** [comment]
I tried with left click before and it didn't work - but it seems to be fine now... Yeah i'll use left click from now on. 

Cheers.
