### ISSUE TITLE
Icon Filters for Categories (e.g. Sea, Island, Continent)

### ISSUE THREAD

**Issue by ryantaplin** [lmachens/arkesia.gg-web#64]
This is a QoL feature, this might be a lot of work, and i'm not sure if 100% possible.

The ability to assign filter types to category types to better streamline the verbose list of icons. Any category that is defined in the 'include' will be displayed on applicable maps.

As an example; 
* Collectible icons should only show on island and continent maps.
* Service icons should only show on continent maps (i.e where there are big cities).
```
{
    name: "Collectibles",
    include: ["Island", "Continent"]
    types: [
      {
        name: "Mokoko Seeds",
        icon: "minimap_symbol_1_121.webp",
        name: "Co-op Quest Area",
        icon: "minimap_symbol_88.webp",
      },
    ],
},
{
    name: "Services",
    include: ["Continent"],
    types: [
      {
        name: "Chef",
        icon: "minimap_symbol_206.webp",
        name: "Sudden Quest Area",
        icon: "minimap_symbol_81.webp",
      },
    ],
},
```

**Comment by lmachens** [comment]
Sounds good, this is for the filter types on node creation only?
Would it be enough to change the sort order in the selection, or is it safe to remove them completely from the list?

**Comment by ryantaplin** [comment]
Yes for node creation only, I guess in the future if you add a way for users to filter specific nodes it may also be useful aswell?

I would say it's safe to remove them completely, if we need to include an icon then we can just change the filter type or category of that icon.

**Comment by lmachens** [comment]
Are there more option?

- Island
- Continent
- World

**Comment by ryantaplin** [comment]
The only other thing I can think of maybe is:
 * Dungeon
But I can't think of anymore off the top of my head right now.
